-- gvs_arh / Supabase
-- Создайте таблицы в SQL Editor.

create table if not exists public.votes (
  id bigint generated by default as identity primary key,
  district_id text not null,
  status text not null check (status in ('yes','no')),
  created_at timestamptz not null default now()
);

create table if not exists public.comments (
  id bigint generated by default as identity primary key,
  district_id text not null,
  author text,
  text text not null check (char_length(text) between 1 and 500),
  created_at timestamptz not null default now()
);

alter table public.votes enable row level security;
alter table public.comments enable row level security;

create policy "public can read votes"
on public.votes for select to anon using (true);

create policy "public can add votes"
on public.votes for insert to anon with check (true);

create policy "public can read comments"
on public.comments for select to anon using (true);

create policy "public can add comments"
on public.comments for insert to anon with check (true);

-- Для настоящего запуска позже добавьте rate limiting/антиспам
-- и более строгие политики.
