-- gvs_arh: Supabase schema
-- Выполните этот SQL в Supabase -> SQL Editor.

create table if not exists public.votes (
  id bigint generated by default as identity primary key,
  district_id text not null,
  status text not null check (status in ('yes','no')),
  voter_id text not null,
  created_at timestamptz not null default now(),
  unique (district_id, voter_id)
);

create table if not exists public.comments (
  id bigint generated by default as identity primary key,
  district_id text not null,
  author text,
  text text not null check (char_length(text) between 1 and 500),
  created_at timestamptz not null default now()
);

alter table public.votes enable row level security;
alter table public.comments enable row level security;

drop policy if exists "votes read" on public.votes;
drop policy if exists "votes insert" on public.votes;
drop policy if exists "votes update" on public.votes;
drop policy if exists "comments read" on public.comments;
drop policy if exists "comments insert" on public.comments;

create policy "votes read" on public.votes for select to anon using (true);
create policy "votes insert" on public.votes for insert to anon with check (true);
create policy "votes update" on public.votes for update to anon using (true) with check (true);

create policy "comments read" on public.comments for select to anon using (true);
create policy "comments insert" on public.comments for insert to anon with check (true);
